### ISSUE TITLE
wildcard module declaration is ignored

### ISSUE THREAD

**Issue by mithodin** [timocov/dts-bundle-generator#231] opened 2022-12-13 08:19 UTC
I am using svgr to automatically create React components from svg files. To make typescript understand this, I have the following declaration file:
```
declare module '*.svg' {
    import { ReactElement, SVGProps } from 'react';
    const content: (props: SVGProps<SVGElement>) => ReactElement;
    export default content;
}
```
However, when I'm trying to create a type definition for an entry point that uses some svg imports, I'm getting a bunch of errors like
```
src/icons/index.ts(3,23): error TS2307: Cannot find module './Checkmark.svg' or its corresponding type declarations.
```
so the declaration seems to be ignored. Not sure if this is a bug or a feature request, but I'd like this to work :-)

**Comment by timocov** [comment] 2022-12-13 23:14
Sorry for redirect reply, but this is kinda duplicate of https://github.com/timocov/dts-bundle-generator/issues/227#issuecomment-1296283628

**Closed by timocov** 2022-12-13 23:14 UTC

**Comment by timocov** [comment] 2022-12-13 23:45
I think it is worth to summarize ideas about that somewhere so I created a discussion where I tried to explain everything and provided ideas how to solve it - https://github.com/timocov/dts-bundle-generator/discussions/232. Feel free to ask any questions there.
