### ISSUE TITLE
importedLibraries not working as expected

### ISSUE THREAD

**Issue by smmoosavi** [timocov/dts-bundle-generator#98] opened 2019-08-04 14:48 UTC
**Bug report**

**Input code**

```ts
import { Command } from 'commander';
export function someFunction(program: Command) {}
```

**Expected output**

```ts
import { Command } from 'commander';
export declare function someFunction(program: Command): void;
```

**Actual output**

```ts
export declare function someFunction(program: Command): void;
```

**Additional context**
Add any other context about the problem here (CLI options, etc)
```js
generateDtsBundle([{
  filePath: 'path-to-project/src/index.ts',
  libraries: {
    importedLibraries: ['commander'],
  },
}])
```

~~note: I am using lerna and yarn workspace~~ I think lerna isn't related to this issue.

**Comment by smmoosavi** [comment] 2019-08-04 15:17
no problem with `react` + `@types/react`

## Input code

```ts
import { Command } from 'commander';
import { ReactNode } from 'react';

export function someFunction(program: Command): ReactNode {
  return null;
}
```
## Expected output

```ts
import { Command } from 'commander';
import { ReactNode } from 'react';

export declare function someFunction(program: Command): ReactNode;

export {};
```


## Actual output

```ts
import { ReactNode } from 'react';

export declare function someFunction(program: Command): ReactNode;

export {};
```

**Comment by timocov** [comment] 2019-08-04 15:34
Hi,

where types for commander is? In `@types` or inside `commander` package itself?

**Comment by timocov** [comment] 2019-08-04 15:38
Ah, nevermind, I reproduced it.

**Comment by smmoosavi** [comment] 2019-08-04 16:39
> where types for commander is? In `@types` or inside `commander` package itself?

inside:
[package.json](https://github.com/tj/commander.js/blob/master/package.json#L37):
```json
{
  "typings": "typings/index.d.ts"
}
```
[typings file](https://github.com/tj/commander.js/blob/master/typings/index.d.ts)

**Comment by smmoosavi** [comment] 2019-08-10 16:53
any update? any workaround?

**Comment by timocov** [comment] 2019-08-16 08:43
Unfortunately no, for custom libraries there is no workaround and even update :(

I believe it should be fixed with that https://github.com/timocov/dts-bundle-generator/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Adetect-import-path-problem issues, but no updates for now.

**Comment by timocov** [comment] 2020-03-09 17:13
@smmoosavi I just dig a bit into the issue and I have no idea how it could be fixed so far.

The issue is that commander package uses declaration merging in very interesting case. The first, it uses commonjs export, so basically you "can't" use es6 imports for that, only `import * as commander` way, but ts allows it... The second, it has 2 properties with the same name `Command` (in namespace `commander` and in interface `CommanderStatic`), and which one will be used depends on context where you use it. For example, if you write `type A = commander.Command` - the `Command` from namespace will be used. But if you'll write `type B = typeof commander.Command` - the `Command` from `CommanderStatic` interface will be taken. That's the problem of the issue - the tool doesn't know that the property from interface could be imported.

As workaround you can use `import * as commander` statement instead (after #103 it's no limitation more), but I'm not sure about the proper fix for that (I have an idea that refactoring the approach of the tool might help, but I'm not sure).

**Closed** 2020-03-18 23:23 UTC
Labels: Bug
