### ISSUE TITLE
`import * as` & `export * as` does not work.

### ISSUE THREAD

**Issue by Patrick-clone** [timocov/dts-bundle-generator#239] opened 2023-03-24 08:19 UTC
**Bug report**
Using `import * as` and or `export * as` results in an empty output `d.ts` file.

**Input code**
one.ts
```ts
export class One {}
```
two.ts
```ts
export class Two {}
```
combine.ts
```ts
import * as One from "./one";
import * as Two from "./two";

export { One, Two };
```

**Expected output**

```ts
// Generated by dts-bundle-generator v7.2.0

declare module One {
    export class One {
    }
}

declare module Two {
    export class Two {
    }
}

export {};
```

**Actual output**

```ts
// Generated by dts-bundle-generator v7.2.0



export {};

```

**Additional context**
Dts-bundle-generator version: 7.2.0
tsconfig.json:
```
{
    "compilerOptions": {
        "strict": false,
        "noImplicitAny": true,
        "rootDir": "./",
        "target": "es2017",
        "outDir": "dist",
        "declaration": true,
        "moduleResolution": "node",
        "preserveConstEnums": true,
        "typeRoots": ["./types"]
    },
    "include": ["src"],
    "exclude": ["node_module"]
}
```

**Comment by timocov** [comment] 2023-03-25 11:51
Duplicate of #134

**Closed by timocov** 2023-03-25 11:51 UTC
