### ISSUE TITLE
Using `as` in import type leads to a broken output

### ISSUE THREAD

**Issue by Bnaya** [timocov/dts-bundle-generator#252] opened 2023-05-09 08:30 UTC
**Bug report**

**Input code**

```ts
// index.ts
import type { Props as AppProps, EsWebComponent } from "./types";
export type { AppProps };
export type TheComponent = EsWebComponent<AppProps>;


// types.ts

export interface Props {
    a: string;
}

export interface EsWebComponent<CProps> extends HTMLElement {
	props: CProps | null;
}
```

**Expected output**

```ts
// Actual output to understand the issue
```

**Actual output**

```ts
// Generated by dts-bundle-generator v8.0.1

interface Props {
	a: string;
	b: Number;
}
export interface EsWebComponent<CProps> extends HTMLElement {
	props: CProps | null;
}
export declare const a = "1";
 // AppProps is an error, does not exists!!!
export type TheComponent = EsWebComponent<AppProps>;

export {
	Props as AppProps,
};

export {};

```

**Additional context**
Add any other context about the problem here (CLI options, etc)

**Comment by timocov** [comment] 2023-06-27 21:19
Duplicate of #184

**Closed by timocov** 2023-06-27 21:19 UTC
