### ISSUE TITLE
Generate Declaration Map

### ISSUE THREAD

**Issue by Zamiell** [timocov/dts-bundle-generator#218] opened 2022-08-10 20:04 UTC
Greetings and thanks for the free tool.

I have a library written in TypeScript. It is consumed by users via npm (like you would expect).

In my library, I include both the source and the compiled output, along with the declaration map. That way, end-users can press F12 on the library functions to very-easily see what the resulting source code looks like. It's really good UX/DX!

Furthermore, the library has some internal functions that shouldn't be put into the auto-complete of end-users. Right now, I just have a crapload of @internal JSDoc comments, but this is pretty terrible. Thus, I would love to use the `dts-bundle-generator` tool to automatically purge any non-publically-exported functions from the generated .d.ts file. However, I can't do that without also breaking the declaration maps, because `dts-bundle-generator` does not seem to generate any declaration maps!

Thus, I am stuck and can't use `dts-bundle-generator` at all. Please consider adding this feature, as I think my use-case is fairly ordinary, all things considered.

**Comment by timocov** [comment] 2022-08-13 10:55
Looks like it is a duplicate of #179. @Zamiell can you post your comment there please?

**Closed by timocov** 2022-08-13 10:55 UTC

**Comment by Zamiell** [comment] 2022-08-13 16:14
A declaration map is different from a source map, so it is not the same.

**Comment by timocov** [comment] 2022-08-13 16:16
Hm, can you elaborate what's the difference please?

**Comment by Zamiell** [comment] 2022-08-13 16:16
Source maps are "foo.js.map" files, and declaration maps are "foo.d.ts.map" files. They serve very different purposes.

**Comment by timocov** [comment] 2022-08-13 16:17
I mean, apart from that a source map is applied to the source code but the declaration map is applied to declaration files?

**Comment by Zamiell** [comment] 2022-08-13 16:19
- Source maps are used by debuggers to generate relevant stack traces at runtime, have TS breakpoints, and so on.
- Declaration maps are simply used by VSCode to map a .d.ts definition to the real source code, so that end-users can press F12 on constants and functions like in the explanation given in the OP.

**Comment by Zamiell** [comment] 2022-08-13 16:22
Furthermore, these are handled by entirely separate compiler flags, such that you can turn on the following combinations:

- No source maps and no declaration maps
- Source maps but no declaration maps
- Declaration maps but no source maps
- Both source maps and declaration maps

**Comment by timocov** [comment] 2022-08-13 16:26
Ok I got you. Since we are here talking about the tool that works with declaration files only I thought that I was clear enough that "source maps for declaration files" means "declaration maps", but it seems it is not. I'll rename that ticket because it meant exactly what you're saying.
