### ISSUE TITLE
Star re-export as namespace from local source files.

### ISSUE THREAD

**Issue by wolfram77** [timocov/dts-bundle-generator#196] opened 2022-04-17 19:47 UTC
**Bug report**

The program i am working on is a main interface for on top of two (raw) sub-interfaces `http` and `websocket` (they represent the nature of connection, are not the http or websocket module). Each interface has a number of functions. The main interface provides a aggregate simpler set of functions that utilize the raw `http` and `websocket` functions. I export main iterface and re-export `http`, `websocket` interfaces as below.

**Input code**

#### http.ts

```ts
export function getProfile(auth: Authorization): Promise<GetProfileResponse> { ... }
export function getFunds(auth: Authorization): Promise<GetFundsResponse> { ... }
```

#### websocket.ts

```ts
export function connectOrderUpdate(auth: Authorization, fn: OnOrderUpdateNotification): Promise<Connection> { ... }
export function subscribeOrderUpdate(conn: Connection): Promise<Response> { ... }
```

#### index.ts

```ts
export * as http      from "./http";
export * as websocket from "./websocket";

export async function getProfile(auth: Authorization): Promise<Profile> { ... }
export async function getFunds(auth: Authorization): Promise<Funds> { ... }
export function connectOrderUpdate(auth: Authorization, fn: OnOrderUpdateNotification): Promise<Connection> { ... }
export async function subscribeOrderUpdate(conn: Connection): Promise<void> { ... }
```

**Expected output**

```ts
export declare namespace http {
  export function getProfile(auth: Authorization): Promise<GetProfileResponse>;
  export function getFunds(auth: Authorization): Promise<GetFundsResponse>;
}

export declare namespace websocket {
  export function connectOrderUpdate(auth: Authorization, fn: OnOrderUpdateNotification): Promise<Connection>;
  export function subscribeOrderUpdate(conn: Connection): Promise<Response>;
}

export async function getProfile(auth: Authorization): Promise<Profile>;
export async function getFunds(auth: Authorization): Promise<Funds>;
export function connectOrderUpdate(auth: Authorization, fn: OnOrderUpdateNotification): Promise<Connection>;
export async function subscribeOrderUpdate(conn: Connection): Promise<void>;
```

**Actual output**

```ts
export async function getProfile(auth: Authorization): Promise<Profile>;
export async function getFunds(auth: Authorization): Promise<Funds>;
export function connectOrderUpdate(auth: Authorization, fn: OnOrderUpdateNotification): Promise<Connection>;
export async function subscribeOrderUpdate(conn: Connection): Promise<void>;
```

**Additional context**

I am using the following command for generating the decalrations file.

```bash
dts-bundle-generator src/index.ts --project tsconfig.json -o index.d.ts --external-imports https,ws
```

**Comment by timocov** [comment] 2022-04-18 09:58
Duplicate of #134

**Closed by timocov** 2022-04-18 09:58 UTC
