### ISSUE TITLE
`export * as NS` is skipped during bundling

### ISSUE THREAD

**Issue by bradzacher** [timocov/dts-bundle-generator#146] opened 2021-01-28 00:28 UTC
**Bug report**

**Input code**

```ts
// file1
export interface Foo {}
export interface Bar {}

// file2
export * as Test from './file1';
```

**Expected output**

```ts
export declare namespace Test {
  export interface Foo {}
  export interface Bar {}
}
```

**Actual output**

```ts
export {};
```

**Additional context**
Add any other context about the problem here (CLI options, etc)

**Comment by timocov** [comment] 2021-01-28 21:44
Duplicate of #134

**Comment by timocov** [comment] 2021-01-28 21:44
I think it's pretty similar to https://github.com/timocov/dts-bundle-generator/issues/134#issuecomment-699616069

**Closed by timocov** 2021-01-28 21:44 UTC
