### ISSUE TITLE
Erroneous complaint about include pattern

### ISSUE THREAD

**Issue by bolinfest** [timocov/dts-bundle-generator#112] opened 2020-04-10 17:47 UTC
**Bug report**

When I run:

```
./node_modules/.bin/dts-bundle-generator -o /tmp/export.d.ts src/index.ts --project tsconfig.json
```

I get an error complaining about missing files:

```
Projects must list all files or use an 'include' pattern.
```

even though my `tsconfig.json` contains:

```
  "include": ["./src/**/*"],
```

which covers the files it claims are missing.

**Input code**

```ts
// place your code here
```

**Expected output**

```ts
// place your code here
```

**Actual output**

```ts
// place your code here
```

**Additional context**
Add any other context about the problem here (CLI options, etc)

**Comment by timocov** [comment] 2020-04-10 19:31
Hi, can you please create a repo with a repro? Or even steps with reproduce with existing repo.

**Comment by timocov** [comment] 2020-04-15 12:43
It's bug.

**Comment by timocov** [comment] 2020-04-15 21:02
Hey @bolinfest, do you have any update here? I faced an error "No inputs were found in config file", but your one looks differ.

> Projects must list all files or use an 'include' pattern.

Looks like you use composite projects, right? See #93

**Comment by timocov** [comment] 2020-04-15 21:18
Yeah. The tool doesn't support composite project's config so far. I can add easily ignoring this error, but without additional information from you I can't tell you whether it helps or not.

**Comment by timocov** [comment] 2020-05-12 17:34
I'm going to close the issue. If you'll have any question or updates - feel free to re-open it.

**Closed by timocov** 2020-05-12 17:34 UTC
